apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=   # ganti dengan username MongoDB dalam format base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==   # ganti dengan password MongoDB dalam format base64

