apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
spec:
  selector:
    app: karsajobs-ui
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 31632
  type: NodePort

